### ISSUE TITLE
Did you upload to pypi.org ?

### ISSUE THREAD

**Issue by laixintao** [tonycpsu/urwid-datatable#3]
Hi I searched pypi but can't find this package(want to install via `pip`), did you upload?

**Comment by tonycpsu** [comment]
No, it's not in pypi.  I'm in the process of moving this widget to my new [panwid](http://github.com/tonycpsu/panwid) project, which I do plan on putting in PyPi at some point once development of it has settled down a bit.

For now, installing from git is the only option.

**Comment by laixintao** [comment]
Thanks, your table is quite helpful and beautiful. But upload to pypi only takes 3 minutes at most...

By the way, I found urwid_utils you depend on not support python3, I submmit a pr(https://github.com/stnbu/urwid_utils/pull/3). Did you still use this on your new project? (panwid is cool too)

**Comment by tonycpsu** [comment]
Thanks for submitting the PR for urwid_utils.  I fixed python 3 compatibility in my own fork but hadn't gotten around to submitting upstream.

**Comment by laixintao** [comment]
But the problem is, when install via `python setup.py install` , easy_install will try to install `urwid_util` via pip, which is the old version of 0.4

**Comment by tonycpsu** [comment]
Use ` pip install -U . --process-dependency-links`
